config/routes.rb
Rails.application.routes.draw do
  root 'subjects#new'
  scope "/:locale" do
    root 'subjects#new'
    resources :subjects
    resources :ratings
  end
  resource :pages
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/emoji.rb
class Emoji < ApplicationRecord
  validates :set, presence: true # Each emoji has to  appear in one of 4 different sets we test.

  # It has to be in the dimension PA (postitive affect) or NA (negative affect)
  validates :dimension, presence: true, inclusion: { in: %w[pa na] }

  # It has to have the polarity «low» or «high». i.e relaxed is NA low but stressed is NA high
  validates :polarity, presence: true, inclusion: { in: %w[low high] }

  # It has to have a verbal representation to the emoji like 😀 = happy
  validates :verbal, presence: true

  has_many :ratings
  has_many :choosens, class_name: 'Rating', foreign_key: 'choosen_id'
  has_many :subjects, through: :ratings

  # Find the distractors of the opposite dimension with the oposite polarity. i.e «na,low» becomes «pa, high»
  def find_distractors
    distractor_dimension = dimension == 'pa' ? 'na' : 'pa'
    distractor_polarity = polarity == 'low' ? 'high' : 'low'
    self.class
        .where(set: set, dimension: distractor_dimension, polarity: distractor_polarity)
        .or(self.class.where(set: set, dimension: dimension, polarity: polarity))
        .where.not(id: id)
  end

  # Calculate the image name or retrun a placeholder if it does not exist
  def image_name
    path = "sets/#{set}/#{dimension}_#{polarity}_#{verbal}"
    # Rails.application.assets.find_asset(path).nil? ? 'placeholder' : path
    path
  end
end

app/models/rating.rb
class Rating < ApplicationRecord
  belongs_to :subject
  belongs_to :emoji
  belongs_to :distractor, class_name: 'Emoji', foreign_key: 'distractor_id'
  belongs_to :choosen, class_name: 'Emoji', foreign_key: 'choosen_id', optional: true # Choosen stimuli either the correct emojo or the distractor

  scope :rated, -> { where.not(rated_at: nil) } # Already rated by the participant
  scope :unrated, -> { where(rated_at: nil) } # Queue of emojis a participant has to rate

  # Order of stimuli presented as buttons
  def stimuli
    reversed ? [distractor, emoji] : [emoji, distractor]
  end

  # Build ratings for a new participant
  def self.build_ratings
    Emoji.where(only_verbal: false).map do |emoji|
      # Find all possible distractors for this emoji
      distractors = emoji.find_distractors.map do |distractor|
        # Count how many times it already was rated
        count_allready_rated = rated.where(emoji: emoji, distractor: distractor).count
        { emoji: emoji, distractor: distractor, count: count_allready_rated }
      end
      # Take the least rated distractor. .
      distractors.sort_by { |x| x[:count] }.first
    end
  end
end

app/models/subject.rb
class Subject < ApplicationRecord
  validates :token, uniqueness: true
  validates :token, presence: true, unless: :new_record?

  before_create :reset_token
  after_create :generate_ratings

  has_many :ratings
  has_many :emojis, through: :ratings

  # Reset the token and proceed until a uniq token is found
  def reset_token
    self.token = generate_token(8) until unique_token?
  end

  # Sample an emoji to rate next
  def rate_next
    ratings.unrated.sample
  end

  private

  # Generates an random token so we don't have to expose the id in public
  def generate_token(size)
    SecureRandom.base64(size).downcase.delete('/+=')[0, size]
  end

  # Check if the generated token is unique, it is rar but in theory it is possible that we generate a token twice.
  def unique_token?
    field = :token
    self.class.where(field => send(field)).blank? && send(field).present?
  end

  # Each participant get a list of rating in advance after create
  def generate_ratings
    Rating.build_ratings.map do |rating|
      ratings.create(emoji: rating[:emoji], distractor: rating[:distractor], reversed: [true, false].sample)
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :set_locale

  # The current subject or participant is deposited in a cookie
  def current_subject
    Subject.find_by(token: cookies.encrypted[:subject_token]) if cookies.encrypted[:subject_token]
  end

  private

  def default_url_options
    { locale: I18n.locale }
  end

  def set_locale
    I18n.locale = params[:locale] || I18n.default_locale
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
end

app/controllers/ratings_controller.rb
class RatingsController < ApplicationController
  before_action :load_rating, only: %i[edit update]

  def edit
    # Whenever a rating is displayed, we timestamp it to calculate the time a partacipant needed to rate the emoji
    @rating.update_attributes(showed_at: DateTime.now)
  end

  def update
    # Set a timestamp for rating to to calculate the time a partacipant needed to rate the emoji
    @rating.update_attributes(rating_params.merge(rated_at: DateTime.now))

    # Redirect to next rating
    next_rating = @subject.rate_next
    # Jump directly to the buttns after the second rating. So we don't have to scroll on mobile
    anchor = 'distractor_buttons' if @subject.ratings.rated.count > 1
    return redirect_to(edit_rating_path(next_rating, anchor: anchor)) if next_rating

    # Otherwise we are at the end and can finish the experiment for this participant
    cookies.delete(:subject_token)
    redirect_to page_path(:finish)
  end

  def rating_params
    params.require(:rating).permit(:choosen_id)
  end

  private

  def load_rating
    @subject = current_subject
    @rating = @subject.ratings.find(params[:id])
  end
end

app/controllers/subjects_controller.rb
class SubjectsController < ApplicationController
  def new
    @subject = current_subject
  end

  # Creates a new session for a participant and directly start with the first rating
  def create
    @subject = Subject.create
    cookies.encrypted[:subject_token] = @subject.token
    redirect_to edit_rating_path(@subject.rate_next)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/flashes_helper.rb
module FlashesHelper
  def user_facing_flashes
    flash.to_hash.slice('alert', 'error', 'notice', 'success')
  end
end

app/views/application/_analytics.html.erb
<% if ENV["SEGMENT_KEY"] %>
  <script type="text/javascript">
    !function(){var analytics=window.analytics=window.analytics||[];if(!analytics.initialize)if(analytics.invoked)window.console&&console.error&&console.error("Segment snippet included twice.");else{analytics.invoked=!0;analytics.methods=["trackSubmit","trackClick","trackLink","trackForm","pageview","identify","reset","group","track","ready","alias","debug","page","once","off","on"];analytics.factory=function(t){return function(){var e=Array.prototype.slice.call(arguments);e.unshift(t);analytics.push(e);return analytics}};for(var t=0;t<analytics.methods.length;t++){var e=analytics.methods[t];analytics[e]=analytics.factory(e)}analytics.load=function(t){var e=document.createElement("script");e.type="text/javascript";e.async=!0;e.src=("https:"===document.location.protocol?"https://":"http://")+"cdn.segment.com/analytics.js/v1/"+t+"/analytics.min.js";var n=document.getElementsByTagName("script")[0];n.parentNode.insertBefore(e,n)};analytics.SNIPPET_VERSION="4.0.0";
    analytics.load("<%= ENV["SEGMENT_KEY"] %>");
    analytics.page();
    }}();
  </script>
<% end %>

app/views/application/_css_overrides.html.erb
<% if Rails.env.test? %>
  <style type="text/css">
    * {
      transition-property: none !important;
    }
  </style>
<% end %>

app/views/application/_flashes.html.erb
<% if flash.any? %>
  <div class="flashes">
    <% user_facing_flashes.each do |key, value| -%>
      <div class="flash-<%= key %>"><%= value %></div>
    <% end -%>
  </div>
<% end %>

app/views/application/_javascript.html.erb
<%= javascript_include_tag :application %>

<%= yield :javascript %>

<%= render "analytics" %>

<% if Rails.env.test? %>
  <%= javascript_tag do %>
    $.fx.off = true;
    $.ajaxSetup({ async: false });
  <% end %>
<% end %>

app/views/layouts/application.slim
doctype html
html
  head
    // Configure default and controller-, and view-specific titles in
       config/locales/en.yml. For more see:
       https://github.com/calebthompson/title#usage
    title= title
    meta charset="utf-8"/
    meta name="ROBOTS" content="NOODP"/
    meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no"/
    = stylesheet_link_tag :application, media: "all" 
    = csrf_meta_tags
  
  body class="#{body_class}"
    .center
      = render "flashes"
      = yield
    = render "javascript" 
    = render "css_overrides"

app/views/pages/finish.de.slim
h1 = 'Besten dank, dass Sie sich die Zeit genommen haben an dieser Untersuchung teilzunehmen.'
p Die von Ihnen generierten Daten sind ein wertvoller Beitrag zu unserer Forschung.
p Sie haben die Untersuchung beendet und können das Fenster jetzt schliessen.

app/views/pages/finish.en.slim
h1 = 'Thank you for taking the time to complete this survey.'
p The data generated by you is a valuable contribution to our research.
p You completed the survey and you can close your browser window now.

app/views/ratings/edit.slim
p = t('.description')

.image
  = image_tag(@rating.emoji.image_name)
#distractor_buttons.distractors
  strong = t('.demand')
  = link_to @rating.stimuli.first.verbal, rating_path(@rating, { 'rating[choosen_id]' => @rating.stimuli.first}), class: 'button first', method: :put
  = link_to @rating.stimuli.last.verbal, rating_path(@rating, { 'rating[choosen_id]' => @rating.stimuli.last}), class: 'button second', method: :put

p.counter = t('.counter', total: @subject.ratings.count, finnished: @subject.ratings.rated.count)

app/views/subjects/_intro.de.slim
article
  p Liebe/r Befragungsteilnehmer/in
  p Wir entwickeln eine <strong>neue Skala zur Erfassung positiver und negativer Aktivierung mittels Emojis</strong>. Positive und negative Aktivierung umfasst unterschiedliche Emotionen wie Begeisterung, Nervosität, Stress, Langeweile oder voller Energie sein. 
  p Wir präsentieren Ihnen <strong><a aria-describedby="footnote-label" href="#emojis" id="emojis-ref">44 verschiedene Emojis mit je zwei Wörtern</a></strong> dazu. Wählen Sie jeweils das Wort, das Ihrem Gefühl nach besser zum Emoji passt. Einige Worte werden sehr ähnlich sein, was beabsichtigt ist.
  p <strong>Antworten Sie spontan, ohne lange nachzudenken!</strong> Auf der Basis aller Antworten wählen wir ein Set von Emojis aus und entwickeln diese weiter.
  p Für diese Befragung benötigen Sie <strong>etwa 5 Minuten.</strong>
  p Wir danken Ihnen herzlich für die Teilnahme!
  p
    | Marc Schreiber, IAP Institut für Angewandte Psychologie der ZHAW (#{mail_to 'scri@zhaw.ch'})
    br
    | Gregor Jenny, Universität Zürich (#{mail_to 'gregor.jenny@uzh.ch'})

  footer
    h2#footnote-label.visually-hidden Fussnoten
    ol.footnote
      li#emojis 
        | Die Emojis wurden von Studierenden der Züricher Hochschule der Künste (ZHdK) erarbeitet. Die Worte entstammen dem deutschen Fragebogen zur Erfassung positiver und negativen Aktivierung (PANAVA-KS; Schallberger, 2005).  
        a.refback href="#emojis-ref" aria-label="Zurück zum Inhalt" ↵

app/views/subjects/_intro.en.slim
p The following questionary is designed to validate nonverbal emojis in correspondence to the verbal terms of the scales for assessing positive/negative activation. It origins from the german scales for assessing positive/negative activation and valence (PANAVA-KS).
p In the following you will see several emojis that expresses one of two words. Your task is to choose the word that best describes the emoji. It generally won't take you longer than 10 minutes.

app/views/subjects/new.slim
h1= t('.title')
p= render 'intro'

hr

- if @subject
  p.text-center
    = link_to t('.proceed'), edit_rating_path(@subject.rate_next)


p.text-center
  strong= link_to t('.create'), subjects_path, method: :post